apiVersion: v1
data:
  ADMIN_API_PORT: MzAxMQ==
  ADMIN_APP_PORT: MzAxMw==
  API_BASE: aHR0cHM6Ly9hcGlzLm9uZWNsb3VkLmNvLm16L2FwaS92Mg==
  API_URL: aHR0cHM6Ly9hcGkubXpvbmUuY2xvdWQv
  BASE_URL: aHR0cDovL2xvY2FsaG9zdDozMDAwLw==
  DNS_API_HOST: aHR0cDovLzEwLjEwNi4zMi4yMDQ6ODA4MS8=
  DNS_API_KEY: MDY4NmU4ZDgtNzAwOC00YzAyLThiM2EtYjBhMzA3YWE4Yjhj
  DNS_API_PASSWORD: RE5TU2VjdXJlIzIwMjA=
  DNS_API_USERNAME: ZG5zQVBJ
  DNS_SECRET_KEY: MDY4NmU4ZDgtNzAwOC00YzAyLThiM2EtYjBhMzA3YWE4Yjhj
  EMAIL_FROM: ZHViYWlwb2NAdnBzaWUuY29t
  FIP_GATEWAY_IP_INCREMENT: Mw==
  FIP_RANGE: MTAuMTAwLjAuMC84
  FRONTEND_URL: aHR0cHM6Ly9teS5tem9uZS5jbG91ZC8=
  GATEWAY_IP_INCREMENT: MQ==
  HIGHT_IP_DECREMENT: MQ==
  ISO_LIB: dGVtcGxhdGVz
  JWT_ACCESS_EXPIRATION_MINUTES: NjA=
  JWT_REFRESH_EXPIRATION_DAYS: MzA=
  JWT_SECRET: NklrcFhqMzQwT0tzM05URTJNak01TTFTc1huUndpVkNKOWV5OEthV0YwSWpveEQ1Y0NJ
  LICENSE_KEY: VjJ4b2MxTXlSa2hUYTJoYVRXMTRVVmxXVm5kVGJGcFpZMFZ3VGxaVVZuZFZNV2hQVTIxS2MxTlVSbHBOUlRWTFZHMTBjMk50VGtkaFJtUlNUVWM0TVZSSE1WZE9WazV4VTJ4d1YwMHlhRE5XTW5SaFZUSlNjbUpJUm1sTmJYaFBXVmQwUjA1V1VuSlVWRkpzVWxSR2QxUXdhSGRVYkZWM1lraHdWRlo2UlRCWk1GcHlaVlphZFZadGNFNWlSbkJYVjFjMWMxTnJOWEppU0ZKUVYwWmFhRlpxUVRGbGJHeHhWR3hrYUUxSGVIZGFSRXB6WVZaWmQxZFVRbGRTZWtFeFdWUkdkMWRXVWxoaVJrSm9WbGQwTTFVeFpITk5Na1pZVTJ4b1VGWXpVbkpXYWs1dll6RnJlbUpGY0U5aVIxRXhWVEp3UzJGR1pFWmlNMlJoVW0xU1NGbDZSbE5YUmtwMFkwZG9VMDF1WjNoV01uaHZWRzFHVm1WRlVsUmlia0p4VkZjeGIxUldaSE5oU0U1c1lUSjRkMXBFU25OaGF6RnlUbFJXV2xadGFFUlVWV1JQVGxaT1dWUnJjR2xXTTJkNlYxUk9jMU50VFhkaVNGSldZbXhhY1ZwV1ZuTmxiRTVZVGxWT2JGWXdiRFZaTUdRMFYyc3dlRk5xV2xSV01uZDZXVlphY21Wc1duVmpSM1JUWlcxM2QxWlVSbXBsUjBaSFlqTnNWMkp1UWt0WlZtaHJZMFprV0UxVlpHaGlWVlkyVm0wMWEyRnRWbFppU0hCVVZucFdVRlJXWkU5VFZrWjFWMjF3YVdKRlduZFdSVlpQVXpKUmVWUnVVbEJXZWtadlZtcE9iMk14VGxoaVJFNW9WakExU2xVeU5VTmhNa3BXVjFoa1dHSkdXbEJaZWtwS1pXeGFkR1JGY0doWFIxSjNWakZhYTFReVRYZGlTRUpyVFcxNGNWUlhjRmRpTVd0M1lVVTVhVTFyYkRaV1Z6VjNVMjFHV1ZwSVFscGhNazB4V1ZWYWQxSnNUblJoUjJ4VFRVWnZlRll4VWt0V01sWldZa2hDYTAxdGVIRlVWRVpMVFd4cmVVMVZaR2xpU0VKYVZrWmtjMVJXUlhkalNFSmhVbTFTVUZreWVIZFhWbFoxWTBWd2FGZEhVbmRYYTJNeFVUSkdjbUpJUW10TmJYaG9XV3hrTkUweFRsaGlSRTVvVmpCd1dWUXhhRmRoUm1SSFUycEtXazFxUm5wYVJscDNUbFpPV1ZScmNHbFdia0l6VjFSSmVGWXdNSGhpUm1oc1UwVTFTMWxXYUd0alJtUlZVMnhrYkZZeFNrbFphMk40WVVaWmQwNVhPV0ZTVjFKWVdsZDBjMk5IVVhsaVJuQnBWak5vTmxkWGRHdGpNbEpYWTBSV1ZGZEZOVXRaYkdoU1pVWmtXRTFXWkd4V01IQXdWbTF3UTFsV1pFWk5XRUpWVWxVMVRGbFZXbkpsYkZaMVVXMTBhVll6WkROWFZscHJWakpXY21KSVFtdE5iWGh2V2xjeGIwNXNUbGhpUkU1b1ZqQndXVlZ0TlZkWGJGbDVWVzVPV0dFeVVrdFpWbHB2VmtkUmVXSkhhRmROUm13elZURmtkMlJ0VmtaT1ZGcFNWMGRvVDFaclpFOU9iRkYzVld4d1QxSXhjRk5VUnpFd1ZXeEdjV0ZGTlU5V1ZGVXlWWHBCZUZOR1VrbGFSelZPVmxSck1sUkdWakJsVm5CWVlqTnNWVlpzU2pWVk1XaERUVWRHY2xaVVRsVmlWM2hIVkd4V2QyRldiRFpYVkZKc1ZsZHpPUT09Cgo=
  LIMIT_IP_PER_VM: MTA=
  LOW_IP_INCREMENT: Ng==
  MAX_ISO_FILE_SIZE: NTAwMDAwMDAwMDA=
  MAX_PHONE_NUMBER_TRIES: NA==
  MAX_REGISTER_TIMES: Mw==
  MAX_ROWS_PER_PAGE: MTAwMA==
  MAX_USAGE: MC44
  MYSQL_CONNECTION_LIMIT: MzAw
  MYSQL_DATABASE: dnBzaWU=
  MYSQL_HOST: MTAuMTA2LjMyLjIwMQ==
  MYSQL_PASS: T25lQ2xvdWRAMDE=
  MYSQL_PORT: MzMwNg==
  MYSQL_USER: dnBzaWU=
  NODE_ENV: cHJvZHVjdGlvbg==
  NODE_TLS_REJECT_UNAUTHORIZED: MA==
  PAYPAL_CANCEL_URL: ''
  PAYPAL_CLIENT_ID: ''
  PAYPAL_CLIENT_SECRET: ''
  PAYPAL_ENVIRONMENT: cHJvZHVjdGlvbg==
  PAYPAL_HOST_API: ''
  PAYPAL_PASSWORD: ''
  PAYPAL_RECURRING_URL: ''
  PAYPAL_RETURN_URL: ''
  PAYPAL_SIGNATURE: ''
  PAYPAL_USERNAME: ''
  PDNS_BASE_URL: aHR0cDovLzEwLjEwNi4zMi4yMDQ6ODA4MS8=
  PDNS_DNS_SERVER: bG9jYWxob3N0
  PDNS_KEY: MDY4NmU4ZDgtNzAwOC00YzAyLThiM2EtYjBhMzA3YWE4Yjhj
  PDNS_NSS: bnMxLm16b25lLmNsb3VkIG5zMi5tem9uZS5jbG91ZA==
  PDNS_PORT: ODA4MQ==
  PDNS_SERVER: bG9jYWxob3N0
  PORT: MzAwMA==
  QUEUE_HOST: cmFiYml0bXE=
  QUEUE_NAME: dnBzaWU=
  QUEUE_PASS: VlBTaWVAMTIzNA==
  QUEUE_PORT: NTY3Mg==
  QUEUE_USER: dnBzaWU=
  RECAPTCHA_SECRET_KEY: NkxjZUR0Y2VBQUFBQVBuYmJRSEdHR3ZCOGxRM0xrMGUxWUI2Y3B2ag==
  REDIS_HOST: dnBzaWUtcmVkaXM=
  REDIS_PORT: NjM3OQ==
  REF_COMM_VAL: MTA=
  REF_SPEND_VAL: NTE=
  SENDER_PHONE_NUMBER: KzE0ODQ0NzcwNTIx
  SEND_GRID_KEY: ''
  SMTP_HOST: bWFpbC52cHNpZS5jb20=
  SMTP_PASSWORD: Yzdaa3M9JmV9LV99
  SMTP_PORT: NDY1
  SMTP_USERNAME: ZHViYWlwb2NAdnBzaWUuY29t
  SNAPSHOT_LIMIT: NQ==
  SOCKET_PORT: ODAwMA==
  SUPPORT_ADMIN_USER: dnBzaWVhZG1pbg==
  SUPPORT_APP_PORT: ODExOA==
  SUPPORT_MONGODB_DATABASE: dnBzaWU=
  SUPPORT_MONGODB_PASSWORD: ''
  SUPPORT_MONGODB_SERVER: MTAuMTA2LjMyLjIwMQ==
  SUPPORT_MONGODB_URI: bW9uZ29kYjovLzEwLjEwNi4zMi4yMDE6MjcwMTcvdnBzaWU=
  SUPPORT_MONGODB_USER: ''
  SUPPORT_PASSWORD: eW1BWHdKUURScDhwNkpyRg==
  SUPPORT_URL: aHR0cHM6Ly9zdXBwb3J0Lm16b25lLmNsb3VkLw==
  TWILIO_ACCOUNT_SID: ''
  TWILIO_AUTH_TOKEN: ''
  VMS_LIMIT: NQ==
  VPC_RANGE_1: MTAuMC4wLjAvOA==
  VPC_RANGE_2: MTcyLjE2LjAuMC8xMg==
  VPC_RANGE_3: MTkyLjE2OC4wLjAvMTY=
  VPSIE_DOCKER: dHJ1ZQ==
  VUE_APP_IDLE_TIME: MzYwMDAwMA==
  VUE_APP_SOCKET_HOSTNAME: YXBpLnZwc2llcG9jLmNvbQo=
  VUE_APP_reCaptchaDevSiteKey: ''
  VUE_APP_reCaptchaProdSiteKey: ''
kind: Secret
metadata:
  name: env-vpsie
  namespace: vpsie
type: Opaque
