---
# RUN COMMAND: ansible-playbook addUser.yaml -i targets -e username=USERNAME -e password=PASSWORD --ask-pass
- name: Create a new user and add to sudoers
  hosts: all
  remote_user: root
  tasks:
    - name: Create a new user
      user:
        name: "{{ username }}"
        password: "{{ password | password_hash('sha512') }}"
        shell: /bin/bash
        append: true
        groups: "sudo,users"
        state: present

    # - name: Add the user to the sudoers group
    #   user:
    #     name: "{{ username }}"
    #     groups: sudoers
    #     append: yes
